name: CI-Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04] # , macos-10.15, windows-2019

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_SYSREQUIRES_MODE: enabled
      INSTALL_DIR: ${{ github.workspace }}/install/

    steps:
    - uses: actions/checkout@v2
       
    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        mkdir build
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
      run: echo "::add-path::/home/runner/.local/bin"

    - name: Get Conan Dependencies
      working-directory: build
      run: cmake -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      working-directory: build
      run: cmake --build . --config Release -j 4
